services:
  - type: worker
    name: telegram-channel-post-preparer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: OWNER_IDS
        sync: false
